language: java
sudo: required

services:
  - docker

stages:
  - pull-build
  - name: build
    if: branch = master OR dev*
  - name: deploy
    if: branch = master OR dev*

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

jobs:
  include:

    # Pull requests
    - stage: pull-build
    script:
     - mvn clean install
    branches:
      except:
      - master
      - dev*
      - feature/*

    # Normal build for dev/master
    - stage: build
    script:
    - mv clean install
    - IMAGE_TAG=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
    - echo $IMAGE_TAG
    - docker build --tag "mrwakecz/corgibot:$IMAGE_TAG" .
    branches:
      only:
      - master
      - dev*

    # Deploy build for dev/master
    - stage: deploy
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push mrwakecz/corgibot:$IMAGE_TAG
    - docker logout
    branches:
      only:
      - master
      - dev*