version: "3"
services:
  bot:
      image: mrwakecz/corgibot:latest
      restart: on-failure:3
      network_mode: "host"
      user: root
      container_name: corgibot
      ports:
        - 5000:5000
      volumes:
        - /srv/corgibot/config.yml:/srv/config.yml
        - /srv/corgibot/logs:/srv/logs
      stop_grace_period: 7200s
      entrypoint:
        - java
        - -jar
        - -Xmx1g
        - -XX:+UseG1GC
        - -XX:+ParallelRefProcEnabled
        - -XX:+UseStringDeduplication
        - corgibot.jar