version: "3"
services:
  bot:
      image: mrwakecz/corgibot:latest@sha256:613848f67461695c74fed6e2fe95631efc339986a04f3348972d07e20d8838ca
      restart: on-failure:3
      network_mode: "host"
      user: root
      container_name: corgibot
      ports:
        - 5000:5000
      volumes:
        - /srv/corgibot/config.yml:/config.yml
        - /srv/corgibot/logs:/logs
      stop_grace_period: 7200s
      entrypoint:
        - java
        - -jar
        - -Xmx1g
        - -XX:+UseG1GC
        - -XX:+ParallelRefProcEnabled
        - -XX:+UseStringDeduplication
        - corgibot.jar