# Pri prvnim spusteni je potreba tento soubor prejmenovat na config.yml!

# Napojeni na SQL
hostname: host
port: 3306
database: database
username: user
password: password

# Nastaveni SQL
minimumConnections: 2
maximumConnections: 5
timeout: 30000

# If is the bot beta (Only for testing)
beta: false

#Discord Token
token: token-from-discord-api

#Imgflip password
imgflipToken: password

#MashapeKey
mashapeGameKey: key